# Generated by Django 2.0.1 on 2018-01-18 23:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myvote', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='option',
            name='votes',
        ),
        migrations.AddField(
            model_name='vote',
            name='option_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='votes', to='myvote.Option'),
        ),
        migrations.AddField(
            model_name='vote',
            name='owner_id',
            field=models.ForeignKey(on_delete='CASCADE', related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
