# Generated by Django 2.0.1 on 2018-01-19 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myvote', '0002_auto_20180118_2336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='option_id',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
