# Generated by Django 2.0.1 on 2018-01-20 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myvote', '0003_auto_20180119_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='poll',
            field=models.ForeignKey(default=1, on_delete='CASCADE', related_name='+', to='myvote.Poll'),
            preserve_default=False,
        ),
    ]
