# Generated by Django 2.0.1 on 2018-01-22 04:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myvote', '0005_auto_20180120_0459'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 22, 4, 18, 42, 333383, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
