# Generated by Django 2.0.1 on 2018-01-22 04:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myvote', '0006_vote_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
