# Generated by Django 2.0.1 on 2018-02-03 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myvote', '0009_auto_20180201_2343'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'ordering': ['-datetime']},
        ),
    ]
