# Generated by Django 2.0.1 on 2018-01-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbio',
            old_name='bio',
            new_name='user',
        ),
        migrations.AddField(
            model_name='userbio',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
